ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 0;

ALTER TABLE ticket_timeline
  ADD COLUMN IF NOT EXISTS to_status VARCHAR(20) NULL;

ALTER TABLE ai_decisions
  ADD COLUMN IF NOT EXISTS provider VARCHAR(8) NOT NULL DEFAULT 'mock';
